---
# --- Docker Compose Configuration --- #
# - Docker Compose V2
# - https://docs.docker.com/compose/compose-file/
#
# Build the Clojure Service from source code
# and run on port 8080
#
# Examples of persistence with Postgres and mysql docker images
# and local data storage to facilitate data restoration

name: "bebes-reborn"

services:
  # --- Clojure Service --- #
  service-service:
    platform: linux/amd64
    # Build using Dockerfile - relative path or Git repository
    build:
      context: ./ # Use Dockerfile in project root
    environment:
      SERVICE_PROFILE: prod        # o prod, si usás la Opción B
      SERVICE_HTTP_PORT: "3000"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: kits
      POSTGRES_PASSWORD: kits
      POSTGRES_SCHEMA: kits
    ports: # host:container
      - 3000:3000
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/system-admin/status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: kits
      POSTGRES_USER: kits
      POSTGRES_PASSWORD: kits
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: