name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Clojure CLI
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest

      - name: Cache Maven (~/.m2)
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run tests (Kaocha)
        run: clojure -M:test/env:test/run

      - name: Build uberjar (tools.build)
        run: clojure -T:build/task uberjar
